version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123asd!@#}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - local
    restart: unless-stopped

  shortener_url_api:
    image: shortener_url_api:latest
    container_name: 'shortener_url_api'
    environment:
      RAILS_ENV: ~
      RAILS_SERVE_STATIC_FILES: ~
      SHORTENER_URL_CLIENT: http://localhost
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123asd!@#
    volumes:
      - gems:/usr/local/bundle 
    ports:
      - '3000:3000'
    networks:
      - local
    depends_on:
      - postgres

  shortener_url_frontend:
    image: shortener_url_frontend:latest
    container_name: shortener_url_frontend
    volumes:
      - ./:/home/frontend
      - /home/frontend/node_modules
    networks:
      - local
    ports:
      - '80:80'
    depends_on:
      - postgres

networks:
  local:
    driver: bridge
    name: local

volumes:
  postgres_data:
    name: postgres_data
  gems:
    name: gems